# classifier params
model_name: "openai/clip-vit-large-patch14"
model_from: "/data/jeisner1/tjbai/checkpoints/imnet_1k.pt"
num_classes: 1000
deep: 1024

# patch params
attack_type: "patch"
patch_r: 0.1
target_label: 965
init_size: 1024

# train params
train_epochs: 20
batch_size: 32
lr: 0.001
streaming: true
num_train_samples: null
num_val_samples: null

checkpoint_dir: "checkpoints"
eval_at: 1000
log_at: 100
name: "v1"
