# classifier params
model_name: "openai/clip-vit-large-patch14"
model_from: "/data/jeisner1/tjbai/checkpoints/imnet_1k.pt"
num_classes: 1000
deep: 1024

# patch params
attack_type: "patch"
patch_r: 0.1
target_label: 965
init_size: 224

# train params
train_epochs: 3
num_workers: 4
batch_size: 32
lr: 0.01
streaming: false
num_train_samples: null
num_val_samples: 10000

# logging, etc
checkpoint_dir: "checkpoints"
eval_at: 15000
log_at: 5000
name: "v6"

# profiling
profile: false
profile_at: 100
