# naming is hard but this is the one

model_name: "openai/clip-vit-large-patch14"
num_classes: 1000
deep: 1024

train_epochs: 10
batch_size: 128
grad_accum_steps: 1
lr: 0.0003

streaming: true
num_workers: 4
num_train_samples: null
num_val_samples: null

eval_at: 2000

checkpoint_dir: '/scratch4/jeisner1/checkpoints'
resume_from: '/scratch4/jeisner1/checkpoints/imnet_best_model_999_Nov05_2332_streaming_b256.pt'

name: streaming_b256
