# classifier params
model_name: "openai/clip-vit-large-patch14"
model_from: "/data/jeisner1/tjbai/checkpoints/imnet_1k.pt"
num_classes: 1000
deep: 1024

# perturbation params
attack_type: "perturbation"
epsilon: 1
target_label: 965

# data loading
train_epochs: 3
num_workers: 1
batch_size: 32
lr: 0.05
streaming: True
num_train_samples: null
num_val_samples: 10000

checkpoint_dir: "checkpoints"
eval_at: 5000
log_at: 5000
name: "perturbation_weak"

profile: false
profile_at: 5

