# classifier params
model_name: "openai/clip-vit-large-patch14"
model_from: "checkpoints/imnet_1k.pt"
num_classes: 1000
deep: 1024

# perturbation params
attack_type: "perturbation"
epsilon: 0.031
target_label: 965

# data loading
train_epochs: 3
num_workers: 1
batch_size: 4
lr: 0.05
streaming: True
num_train_samples: 1000
num_val_samples: 10

checkpoint_dir: "checkpoints"
eval_at: 10
log_at: 5
name: "perturbation_weak"

profile: false
profile_at: 5
